-- ============================================================
-- ⚠️  此文件已废弃（moved）
-- ============================================================
-- 数据库 schema 的唯一权威源（source of truth）：
--   goods-insight-infra/mysql/init/02-user.sql
--
-- 历史：此文件早期是用户服务 schema 的副本，后因 docker MySQL
--       init 只加载 infra/mysql/init/*.sql，导致此处与运行时 DB 漂移。
--
-- 维护规则：
--   1. 只改 goods-insight-infra/mysql/init/02-user.sql
--   2. 改完跑 `docker compose down -v && docker compose up -d` 验证 fresh init 一致
--   3. 已部署环境的 DB 需要手动跑 ALTER（或重新 init）
--
-- 此文件保留仅为兼容旧 IDE 跳转习惯，不参与构建。